version: "3.8"

services:
  opm:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - "./src:/opt/project/src"
      - "./data:/opt/project/data"
      - "./config:/opt/project/config"
      - "./examples:/opt/project/examples"
      - "./notebooks:/opt/project/notebooks"
    tty: true
